### ISSUE TITLE
Time Series data

### ISSUE THREAD

**Issue by ShaniGam** [ZhongxiaYan/video_prediction#1]
First of all, great work!
You claim that you got the best results when used 'villegas_combined_conv4' but I saw that it doesn't contain any LSTM/RNN layers. How do you use the fact that this is a time series data to make better predictions?

**Comment by ZhongxiaYan** [comment]
Hey! The LSTM stage is before the analogy network stage (villegas_combined_conv4 is one implementation of the analogy network that we tried). The LSTM predicts the future pose coordinates first, and then we feed the predicted pose into the analogy network.
