### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Kamel-schbock** [ZhongxiaYan/video_prediction#3]
Hey Yan,
Thank you for sharing your work. I have question related to some organization stuff in the implementation. 
Can you please provide me with more details about how should i run the code completely and successfully in order to observe the same results that you provided in the repository?
* In data folder there are directories (squats_L_1 , squats_L_1_gray , squats_L_13_gray, Penn_action) with the corresponding dataset.py files, but there is no (squat) folder with the corresponding datasets,should i create one? 
* I downloaded (Penny_action) datasets. In notebooks/Preprocess  should i specify the path of the downloaded (Penn_action path)  to obtain (squat datasets) ? What i noticed is that, this Preprocess provides (squats_labels_multiple and squats_labels as folders )  so should i create squad folder and move both previous folders into?
* In models folder, what is the best one ?
* What is the difference between src/lstm and notebooks/LSTM?
Thank you for your help
Best regards

**Comment by ZhongxiaYan** [comment]
Hi Kamel, sorry unfortunately we don't have any documentations beyond what we provided and it's been a long time so we probably don't remember how to run these beyond what we wrote. I suggest trying to add whatever you need to add to make our script paths work.

It seems like models/villegas_combined_conv4/adam_l2_100_feat/ was our best version

**Comment by Kamel-schbock** [comment]
Hey Yan,
Thank you for your answer.
I did many tries, but not succeeded. I can just successfully run  LSTM and Deep_seq2seq in notebooks folder .
If you can remember, it will be very helpful for me especially how to run the scripts in src folder.
Thanks
