### ISSUE TITLE
squat directory

### ISSUE THREAD

**Issue by Katreenlooper** [ZhongxiaYan/video_prediction#4]
Hey,
Thanks for your work.
Where can i find squat directory in analogy_network.ipynb?

for video in os.listdir('squats/')
videos[video] = []
for frame in os.listdir('squats/' + str(video) + '/'):
filename = 'squats/' + str(video) + '/' + str(frame)
videos[video].append(imread(filename))

Preprocess.ipynb generates two directories of (squat_labels, squat_labels_multiple) but there is no squat directory..
Thanks

**Comment by ZhongxiaYan** [comment]
I think you just rename it. We left the name general and only preprocessed what we needed I think
